### ISSUE TITLE
Thermostats Home Kit Error

### ISSUE THREAD

**Issue by Domreis** [KraigM/homebridge-wink#21]
First I want to say thank you for all of your work on this plugin. It has been awesome, and continues to improve with every release. 

Currently I am having an issue with Thermostats. I am able to query and view the status of the thermostat, but am unable to update/change the temperature from either Sir or any HomeKit app. The homekit apps return an error, in my case "Eve" states "HomeKit reported a communication failure. Please try again."

I am using a Honeywell WiFi thermostat. I do have a nest I can install and test with to see if that account integration works.

Thanks!

**Comment by pdlove** [comment]
Mine is working with Ecobee and the Vivint Z-wave thermostat. Is it making the change on the thermostat, reporting an error?

**Comment by Domreis** [comment]
Yes, it is making a change that reports the error. For example I ask Siri to set the thermostat to 70* and she reports she is unable to do that at this time. I am however able to ask Siri " what is the thermostat set for" and she replies with an appropriate answer. 

I get the Homekit communication error within the eve app when I also try and adjust the temperature.

Another issue I am having is with my Schlage Z-Wave lock. The lock name is "Front Door" within the Wink app, and that data is moved over into home bridge. When I ask Siri to unlock the front door she replies with "I am sorry would you like all the doors unlocked" if I say yes both the front door and garage doors unlock. 

Thanks.

**Comment by pdlove** [comment]
Do you have a light called front door as well? I have a lock and light called front door, and I have to tell Siri to unlock the front door lock.

**Comment by KraigM** [comment]
@Domreis see if your issues are fixed in version 1.1.0

**Comment by steveclynn** [comment]
I'm having the same issue Domreis commented on Jan 15, 2016. My eve app keeps stating "HomeKit reported a communication failure. Please try again." whenever i attempt to change the thermostat manually and Siri can't seem to reach the thermostat either. Could you please point me in the direction of the solution you provided.

Also, I randomly get the following error that crashes homebridge:

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:68:19)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
raw message <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
^C[7/13/2016, 11:12:07 PM] Got SIGINT, shutting down Homebridge...

Any help would be appreciated.
