### ISSUE TITLE
"Unexpected end of input" Error

### ISSUE THREAD

**Issue by khkremer** [KraigM/homebridge-wink#30]
When I add the Wink plugin, I get the following error message when I start HomeBridge:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:68:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
raw message  
/usr/local/lib/node_modules/homebridge-wink/index.js:118
					for (var i = 0; i < devices.data.length; i++) {
					                           ^

TypeError: Cannot read property 'data' of undefined
    at /usr/local/lib/node_modules/homebridge-wink/index.js:118:33
    at /usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:241:9
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:75:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

Here is the Wink related portion from my config.son file:

    {
                "platform": "homebridge-wink.Wink",
                "name": "Wink",
                "client_id": "xxxxxx",
                "client_secret": "xxxxxx",
                "username": "xxxxx",
                "password": "xxxxxx",
                "hide_groups": ["garage_doors", "thermostats"],
                "hide_ids": []
        }

Any advice about how to fix this? 

Thanks.

**Comment by cmcarver** [comment]
I am having the same issue.  Any updates on this?

**Comment by cmcarver** [comment]
I figured out the issue.  Mine was a silly mistake of wrong password.  I must have changed the username when I used the correct pw then never used the correct user/people together.  I had to go into the wink app to verify which pw I needed on my door lock security.  But now it works.

**Comment by nimustan** [comment]
I am having the same problem. Any advice please?

**Comment by jpborjas** [comment]
Same here, I had the same error, and I found a space in the username.

**Comment by nimustan** [comment]
I was told no spaces

**Comment by apressly** [comment]
same issue, i have the correct username and password, how  do i fix this?
