### ISSUE TITLE
Error Mesage?

### ISSUE THREAD

**Issue by benw525** [KraigM/homebridge-wink#33]
Anyone know what this is and how it can be fixed?

It seems to happen anytime I leave homebridge running for a few hours. 

SyntaxError: Unexpected token <
at Object.parse (native)
at IncomingMessage. (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:68:19)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:913:12)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)
raw message <!DOCTYPE html>

<br> html, body, iframe { margin: 0; padding: 0; height: 100%; }<br> iframe { display: block; width: 100%; border: none; }<br> 
Application Error

<br> <p>Application Error</p><br>

**Comment by benw525** [comment]
This error happens often but does not seem to impair functionality. It is mostly a curiosity to this layman.
