### ISSUE TITLE
TypeError: Path must be string. Received null

### ISSUE THREAD

**Issue by flipit** [KraigM/homebridge-wink#37]
Trying to run the plugin and getting the following error - 

[5/22/2016, 5:05:43 PM] ERROR LOADING PLUGIN homebridge-wink:
[5/22/2016, 5:05:43 PM] TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-wink/node_modules/config-file/index.js:17:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)

**Comment by frshbeetz** [comment]
Same Here:

```
6/6/2016, 9:53:01 PM] ====================
[6/6/2016, 9:53:01 PM] ERROR LOADING PLUGIN homebridge-wink:
[6/6/2016, 9:53:01 PM] TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/config-file/index.js:17:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
[6/6/2016, 9:53:01 PM] ====================
```

**Comment by flipit** [comment]
I downgraded my node installation to v5. Working fine on my pi3 now.

**Comment by frshbeetz** [comment]
I used nvm https://github.com/creationix/nvm to install the version I needed. That did the trick, thanks!

**Comment by mph88** [comment]
I tried setting this up this plugin in a freenas jail and I run into the same error as above, however, if I try and downgrade node, I can't downgrade npm. Is there another way around this so as to use the most recent version of node, 6.2.1?

**Comment by xjones** [comment]
Any chance someone is working on a permanent fix for this using current versions of node, nom, etc?

**Comment by entmike** [comment]
Same issue here.

**Comment by earlthesquirrel** [comment]
Same issue here.   Are you going to release a fix for this??
