### ISSUE TITLE
Error: The requested accessory 'Wink' was not registered by any plugin.

### ISSUE THREAD

**Issue by mdod** [KraigM/homebridge-wink#44]
**Hi,
I am trying to run Homebridge on my Raspberry Pi, and whenever I start it, I can't get my Wink accessories to work and I get this error:** 

Error: The requested accessory 'Wink' was not registered by any plugin.
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:233:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**I have installed the plugin using:** `npm install -g homebridge-wink`
**And I have Node.js installed, version 4.4.7.**

**Although, if I run that command again, I get:**

pi@raspberrypi:~$ sudo npm install -g homebridge-wink
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
homebridge-wink@1.1.1 /usr/lib/node_modules/homebridge-wink
└── wink-js@0.1.1 (async@1.5.2, debug@2.2.0, config-file@0.1.8)

**Is that a problem? ^**

**Let me know if I can provide more information,
Thanks**

**Comment by brianwarehime** [comment]
Seeing the same thing as well:

`[7/8/2016, 8:40:56 PM] ERROR LOADING PLUGIN homebridge-wink:
[7/8/2016, 8:40:56 PM] TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-wink/node_modules/config-file/index.js:17:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:4:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
[7/8/2016, 8:40:56 PM] ====================
[7/8/2016, 8:40:56 PM] Loaded plugin: homebridge-xbox-one
[7/8/2016, 8:40:56 PM] Registering accessory 'homebridge-xbox-one.Xbox'
[7/8/2016, 8:40:56 PM] ---
[7/8/2016, 8:40:56 PM] Loaded config.json with 3 accessories and 2 platforms.
[7/8/2016, 8:40:56 PM] ---
[7/8/2016, 8:40:56 PM] Loading 2 platforms...
[7/8/2016, 8:40:56 PM] [Security Panel] Initializing Alarmdotcom platform...
/usr/lib/node_modules/homebridge/lib/api.js:106
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Wink' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:106:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
`

**Comment by bradleyrawleigh** [comment]
@brianwarehime I've tried to use the xbox one pluggin previously and failed, how did you get yours working properly? mine is connected through ethernet with a set IP on my network.....

**Comment by brianwarehime** [comment]
@bradleyrawleigh I don't think I did anything special to get it working. Here's the part of the config for mine:
`
{
  "accessory": "Xbox",
  "name": "Xbox",
  "ipAddress": "192.168.1.185",
  "liveId": "FD11A74D6F918BD3"
}
`

**Comment by bradleyrawleigh** [comment]
ill try it again, Thanks @brianwarehime

**Comment by dcgrove** [comment]
Has anyone been able to figure this out?  I have Homebridge running on one server, but want to install it on more stable hardware and am getting this message when trying to start it.


clayton@bigserver:~$ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[9/16/2016, 9:34:32 AM] ====================
[9/16/2016, 9:34:32 AM] ERROR LOADING PLUGIN homebridge-wink:
[9/16/2016, 9:34:32 AM] TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-wink/node_modules/config-file/index.js:17:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
[9/16/2016, 9:34:32 AM] ====================
[9/16/2016, 9:34:32 AM] No plugins found. See the README for information on installing plugins.
[9/16/2016, 9:34:32 AM] Loaded config.json with 1 accessories and 1 platforms.
[9/16/2016, 9:34:32 AM] ---
[9/16/2016, 9:34:32 AM] Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:106
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Wink' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:106:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
clayton@bigserver:~$

**Comment by chado99** [comment]
I'm having the same issue. I'm running a RPi3 version 6.6 of node. Just did clean install of everything.

My error:
_[9/21/2016, 10:57:06 PM] ERROR LOADING PLUGIN homebridge-wink:
[9/21/2016, 10:57:06 PM] TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-wink/node_modules/config-file/index.js:17:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:4:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-wink/index.js:2:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:112:14)
[9/21/2016, 10:57:06 PM] ====================_

**Comment by vogelboy** [comment]
Same exact problem... anyone figure it out? I also did a fresh install on my RPi with Node 6.6. I previously had it running for MONTHS just fine... maybe I need to go back to Node 4.x? Anyone? Bueller?

**Comment by dcgrove** [comment]
I fixed this by going to Node 4.5.

**Comment by vogelboy** [comment]
Thanks!! I'll give it a shot tonight.

**Comment by luken** [comment]
Downgrading to 4.5 worked for me, but I had to npm uninstall homekit packages then reinstall, as discussed in #53

**Comment by chado99** [comment]
Yes, I solved ignored by downgrading to the last Node LTE version which was 4.5. Uninstall everything then reinstall everything (everything being homeveidge node and related packages)
