### ISSUE TITLE
Version mismatch, how to correct?

### ISSUE THREAD

**Issue by jack-hub** [KraigM/homebridge-wink#53]
I am an OLD dos guy in a MacOS world. I got homebridge installed and running. But when I installed the Wink plugin, I get this version error. Some of the solutions I found were over my head (doesn't take much) and I was never sure the solution I found was for this problem -- don't want to make things worse. 

Any help appreciated and if this the wrong way to get help, let me know that too. first time submitting an issue on GitHub.
-Thanks 

/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by luken** [comment]
I'm new to npm / js world as well, but maybe upgrading your packages?  Something like

npm upgrade -g mdns

or upgrade everything

npm upgrade -g

**Comment by luken** [comment]
While trying to fix the issue I had (logged already as #44) i triggered this same issue.   The exact point I triggered it at was just after downgrading from node version 6 to node version 4 (as recommended in that thread).  

By uninstalling homebridge (I did accessory packages as well) then reinstalling this issue went away. In my case it was:

npm uninstall -g --unsafe-perm homebridge-sonos
npm uninstall -g --unsafe-perm homebridge-wink
npm uninstall -g --unsafe-perm homebridge-nest
npm uninstall -g --unsafe-perm homebridge


npm install -g --unsafe-perm homebridge
npm install -g --unsafe-perm homebridge-sonos
npm install -g --unsafe-perm homebridge-wink
npm install -g --unsafe-perm homebridge-nest

**Comment by chado99** [comment]
I had a similar issue (though the lines ere one off). Not sure exactly what fixed t but I believe it to be the versions of nodde you're running. I was running bode 6.6 and having issues. I uninstalled everything (himebridgd,node, related packages)  then reinstalled node 4.5 (the latest/most current  node lTE version).   Think the command to. Heck is node -v.
