### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Jborn4christ** [KraigM/homebridge-wink#78]
I made some changes a while back due to wink api issues, and have since done some updates, and assume something is broken in the index.js or somewhere similar. Any help would be appreciated. Still using my v1 api info until they send me v2 secret/question.

[2/1/2017, 7:28:15 PM] Loaded plugin: homebridge-camera-ffmpeg
[2/1/2017, 7:28:15 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2/1/2017, 7:28:15 PM] ---
[2/1/2017, 7:28:19 PM] Loaded plugin: homebridge-liftmaster
[2/1/2017, 7:28:19 PM] Registering accessory 'homebridge-liftmaster.LiftMaster'
[2/1/2017, 7:28:19 PM] ---
[2/1/2017, 7:28:26 PM] Loaded plugin: homebridge-myq
[2/1/2017, 7:28:26 PM] Registering platform 'homebridge-myq.MyQ'
[2/1/2017, 7:28:26 PM] ---
[2/1/2017, 7:28:37 PM] Loaded plugin: homebridge-nest
[2/1/2017, 7:28:37 PM] Registering platform 'homebridge-nest.Nest'
[2/1/2017, 7:28:37 PM] ---
[2/1/2017, 7:28:43 PM] Loaded plugin: homebridge-wink
[2/1/2017, 7:28:43 PM] Registering platform 'homebridge-wink.Wink'
[2/1/2017, 7:28:43 PM] ---
[2/1/2017, 7:28:43 PM] Loaded config.json with 1 accessories and 1 platforms.
[2/1/2017, 7:28:43 PM] ---
[2/1/2017, 7:28:43 PM] Loading 1 platforms...
[2/1/2017, 7:28:43 PM] [Wink] Initializing Wink platform...
[2/1/2017, 7:28:43 PM] [Wink] Fetching Wink devices.
[2/1/2017, 7:28:43 PM] Loading 1 accessories...
[2/1/2017, 7:28:43 PM] [Garage Door] Initializing LiftMaster accessory...
Load homebridge-camera-ffmpeg.Camera-ffmpeg
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:69:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
raw message 
/usr/local/lib/node_modules/homebridge-wink/index.js:121
					for (var i = 0; i < devices.data.length; i++) {
					                           ^

TypeError: Cannot read property 'data' of undefined
    at /usr/local/lib/node_modules/homebridge-wink/index.js:121:33
    at /usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:242:9
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:76:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Jeremys-Mac-mini:homebridge jeremychambers$

**Comment by cheychey** [comment]
I have the same exact error. Where you able to fix it?
